up:
	migrate -database 'postgres://postgres:password@localhost:5432/postgres?sslmode=disable' -path ./migrations up

down:
	migrate -database 'postgres://postgres:password@localhost:5432/postgres?sslmode=disable' -path ./migrations down
